export const dynamicMetricsStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3, // Consistent 24px spacing between all sections
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 300,
    textAlign: 'center',
    p: 4,
  },
  summaryHeader: {
    p: 3,
    borderRadius: 3,
    background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.1) 0%, rgba(59, 130, 246, 0.1) 100%)',
    border: '1px solid',
    borderColor: 'primary.light',
  },
  summaryContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 2,
  },
  summaryTitle: {
    fontWeight: 700,
    color: 'text.primary',
    mb: 0.5,
  },
  costSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
  },
  costItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
  },
  sectionTitle: {
    fontWeight: 700,
    color: 'text.primary',
    mb: 2,
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: -8,
      left: 0,
      width: 40,
      height: 3,
      backgroundColor: 'primary.main',
      borderRadius: 2,
    },
  },
  chartPaper: {
    p: 3,
    borderRadius: 3,
    height: '100%',
    background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.05) 100%)',
    backdropFilter: 'blur(10px)',
    border: '1px solid',
    borderColor: 'divider',
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      boxShadow: 3,
    },
  },
  detailsPaper: {
    p: 3,
    borderRadius: 3,
    background: 'linear-gradient(135deg, rgba(34, 197, 94, 0.05) 0%, rgba(59, 130, 246, 0.05) 100%)',
    border: '1px solid',
    borderColor: 'success.light',
  },
  detailsTitle: {
    fontWeight: 700,
    color: 'text.primary',
    mb: 3,
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    p: 2,
    borderRadius: 2,
    backgroundColor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
  },
  tagsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
  },
  tagChip: {
    fontSize: '0.75rem',
    height: 24,
  },
};
